# Hydrogen
spacing = 3
padding = 0
hide_ascii = false
prefer_small_ascii = true
separator = "󰜴"
key_color = "Cyan"
separator_color = "White"

[palette]
type = "Full"
visible = false

[bar]
glyph = ""
symbol_open = '['
symbol_close = ']'
hide_delimiters = true
visible = true

[box]
# "plain", "thick", "rounded" or "double"
border = "rounded"
visible = true

[box.inner_margin]
x = 1
y = 0

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "Local IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU"
cpu = "CPU Name"
gpu = "GPU Name"
disk_space = "Disk Space"
