#!/bin/bash

total="xdotool get_num_desktops"
icon1=○
icon2=◎
icon3=●

leftwm-state 2> /dev/null | while true read line; do
  currwp=$((`xdotool get_desktop`))
  for i = 0..$total
  # Run jaq command on the output and print the result
  echo "$line" | jaq -r '.workspaces[0].tags[] | select(.mine == true) | .index'
done

bspc subscribe desktop_focus node_add node_remove 2> /dev/null | while read line; do
currwp=$((`xdotool get_desktop`))
for (( i = 0; i < $total; i++));
do
  if [[ $i -eq $currwp ]]
  then
    $eww update wp$i=$icon3
  else
    [[ `bspc query -N -d $i | wc -l` -gt 0 ]] && $eww update wp$i=$icon2 || $eww update wp$i=$icon1 
  fi;
done
echo cycle
done
