dpi-aware=no

icons-enabled=yes
icon-theme=Papirus-Dark
font=CaskaydiaCove Nerd Font:weight=bold:size=16
line-height=30

fields=name,generic,comment,categories,filename,keywords
terminal=foot -e
prompt="❯   "

layer=overlay
; anchor=top-left
width=30

[colors]

; gruvbox colours
; bg #282828 #928374
; fg #A89984 #EBDBB2
; red #CC241D #FB4934
; orange #D65D0E #FE8019
; yellow #D79921 #FABD2F
; green #98971A #B8BB26
; cyan #689D6A #8EC07C
; blue #458588 #83A598
; magenta #B16286 #D3869B

; Background color. Default: fdf6e3ff.
background=282828ff
; Text (foreground) color of unselected entries. Default: 657b83ff.
text=EBDBB2ff
; Text (foreground) color of prompt character(s). Default: 586e75ff.
prompt=458588ff
; Text (foreground) color of the placeholder string. Default: 93a1a1ff.
placeholder=458588ff
; Text (foreground) color of input string. Default: 657b83ff.
input=B8BB26ff
; Text (foreground) color of the matched substring. Default: cb4b16ff.
match=458588ff
; Background color of the selected entry. Default: eee8d5ff.
selection=689D6Aff
; Text (foreground) color of the selected entry. Default: 586e75ff.
selection-text=EBDBB2ff
; Text  (foreground)  color of the matched substring of the selected entry. Default: cb4b16ff.
selection-match=CC241Dff
; The color of the match count stats printed at the right-hand side of  the input prompt. See COLORS. Default: 93a1a1ff.
counter=HEX
; Border color. Default: 002b36ff.
border=D79921ff

[border]
width=5
radius=40

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cursor-right-word=Mod1+w
