local dir = os.getenv("HOME") .. "/.config/awesome/theme/icons"

return {

	write = dir .. "/write.png",
	calendar = dir .. "/calendar.png",
	mail = dir .. "/mail.png",
	firefox = dir .. "/firefox.png",
	vid = dir .. "/vid.png",
	call = dir .. "/call.png",
	img = dir .. "/img.png",
	code = dir .. "/code.png",
	chrome = dir .. "/brave.svg",
	social = dir .. "/forum.svg",
	folder = dir .. "/folder.svg",
	music = dir .. "/music.svg",
	game = dir .. "/google-controller.svg",
	lab = dir .. "/flask.svg",
	--others
	menu = dir .. "/menu.svg",
	close = dir .. "/close.svg",
	logout = dir .. "/logout.svg",
	sleep = dir .. "/power-sleep.svg",
	power = dir .. "/power.svg",
	lock = dir .. "/lock.svg",
	restart = dir .. "/restart.svg",
	search = dir .. "/magnify.svg",
	volume = dir .. "/volume-high.svg",
	brightness = dir .. "/brightness-7.svg",
	chart = dir .. "/chart-areaspline.svg",
	memory = dir .. "/memory.svg",
	harddisk = dir .. "/harddisk.svg",
	thermometer = dir .. "/thermometer.svg",
	plus = dir .. "/plus.svg",
}
