general {
  # runs hyprlock if not already running
  lock_cmd = pidof hyprlock || hyprlock 
  # kills hyprlock when unlocking
  unlock_cmd = killall hyprlock 
  # ensures that the session is locked before going to sleep
  before_sleep_cmd = playerctl pause; loginctl lock-session
  # make sure the screen is on after you go to sleep!
  # after_sleep_cmd = niri msg output eDP-1 on
  # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam) (fullscreen stuff)
  ignore_dbus_inhibit = false
}

# Warning your screen's about to lock, dim the screen
listener {
  timeout = 270
  on-timeout = brightnessctl -s set 10; notify-send "Your screen will turn off in 30s"
  on-resume = brightnessctl -r
}

# Screenlock
listener {
  timeout = 300
  on-timeout = loginctl lock-session 
  on-resume = notify-send "Back again is it arsepiece?"
}

# Turn off screen
listener {
  timeout = 310
  on-resume = niri msg output eDP-1 off
  on-resume = niri msg output eDP-1 on
}

# Suspend
listener {
  timeout = 1800
  on-timeout = systemctl suspend
  # on-resume = notify-send "Welcome back"
}
