#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Replace the last <down> file with this one, if this theme is <current>
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# load the theme file
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# load the background using feh if it is installed
if [ -x "$(command -v feh)" ]; then
    feh --bg-scale $(ls $SCRIPTPATH/background* | shuf -n 1)
fi

# start eww and open windows
eww daemon &
eww open-many left_bar centre_bar right_bar
