# format = '$all$directory$character'
add_newline = false
# A minimal left prompt
format = """$directory$character"""
# palette = "catppuccin_frappe"
palette = "gruvbox"
# move the rest of the prompt to the right
right_format = """$all"""

# symbols
[aws]
symbol = "  "
[buf]
symbol = " "
[c]
symbol = " "
[conda]
symbol = " "
[dart]
symbol = " "
[directory]
read_only = " "
[docker_context]
symbol = " "
[elixir]
symbol = " "
[elm]
symbol = " "
[fossil_branch]
symbol = " "
[git_branch]
symbol = " "
[golang]
symbol = " "
[guix_shell]
symbol = " "
[haskell]
symbol = " "
[haxe]
symbol = "⌘ "
[hg_branch]
symbol = " "
[java]
symbol = " "
[julia]
symbol = " "
[lua]
symbol = " "
[memory_usage]
symbol = " "
[meson]
symbol = "喝 "
[nim]
symbol = " "
[nix_shell]
symbol = " "
[nodejs]
symbol = " "
[package]
symbol = " "
[pijul_channel]
symbol = "🪺 "
[python]
symbol = " "
[rlang]
symbol = " "
[ruby]
symbol = " "
[rust]
symbol = "󱘗 "
[scala]
symbol = " "
[spack]
symbol = "🅢 "

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.gruvbox]
rosewater = "#ffdab9"
flamingo = "#e5b8b7"
pink = "#d3869b"
mauve = "#b16286"
red = "#cc241d"
maroon = "#af3a03"
peach = "#d79921"
yellow = "#fabd2f"
green = "#8ec07c"
teal = "#8ec07c"
sky = "#83a598"
sapphire = "#458588"
blue = "#7c6f64"
lavender = "#d3869b"
text = "#ebdbb2"
base = "#282828"
mantle = "#3c3836"
crust = "#504945"
# note: these are just from catppuccin_frappe! fix!
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"

# [os.symbols]
# Alpine = " "
# Amazon = " "
# Android = " "
Arch = " "
# CentOS = " "
# Debian = " "
# DragonFly = " "
# Emscripten = " "
# EndeavourOS = " "
# Fedora = " "
# FreeBSD = " "
# Garuda = "﯑ "
# Gentoo = " "
# HardenedBSD = "ﲊ "
# Illumos = " "
# Linux = " "
# Macos = " "
# Manjaro = " "
# Mariner = " "
# MidnightBSD = " "
# Mint = " "
# NetBSD = " "
# NixOS = " "
# OpenBSD = " "
# openSUSE = " "
# OracleLinux = " "
# Pop = " "
# Raspbian = " "
# Redhat = " "
# RedHatEnterprise = " "
# Redox = " "
# Solus = "ﴱ "
# SUSE = " "
# Ubuntu = " "
# Unknown = " "
# Windows = " "
