require "squish.options"
require "squish.keymaps"
require "squish.plugins"
require "squish.treesitter"
require "squish.colorscheme"
require "squish.telescope"
require "squish.autopairs"
require "squish.neoscroll"
require "squish.commentary"
require "squish.surround"
require "squish.lightspeed"
require "squish.shade"
require "squish.indentguides"
require "squish.cmp"
require "squish.lualine"
require "squish.lsp"
require "squish.devicons"
-- require "squish.nvim-tree"
require "squish.bufferline"
require "squish.neorg"
require "squish.alpha"
require "squish.gitsigns"
require "squish.impatient"
require "squish.autocommands"
require "squish.chartoggle"
require "squish.substitute"
require "squish.ts-context"
require "squish.renamer"
require "squish.toggleterm"
require "squish.neoclip"
require "squish.vimtex"
require "squish.scrollbar"
-- require "squish.whichkey"
-- require "squish.project"
