require "squish.keymaps"
require "squish.plugins"
require "squish.autocommands"
require "squish.options"
require "squish.impatient"

-- colorschemes
require "squish.cc_material"
require "squish.cc_tundra"
require "squish.cc_catpuccin"
require "squish.cc_gruvbox"
require "squish.cc_rosepine"
-- require "squish.styler"
require "squish.colorscheme"

-- require "squish.nui"
require "squish.cmp"
require "squish.lsp-inlayhints"
require "squish.telescope"
require "squish.treesitter"
require "squish.autopairs"
require "squish.neoscroll"
require "squish.commentary"
-- require "squish.neogen"
require "squish.surround"
require "squish.leap"
require "squish.leap_spooky"
require "squish.indentguides"
require "squish.lsp"
require "squish.dressing"
require "squish.devicons"
require "squish.nvim-tree"
require "squish.bufferline"
require "squish.neorg"
require "squish.alpha"
-- require "squish.chartoggle"
require "squish.substitute"
require "squish.ts-context"
require "squish.trouble"
require "squish.toggleterm"
require "squish.vimtex"
require "squish.winbar"
require "squish.numb"
require "squish.notify"
-- require "squish.noice"
require "squish.dial"
require "squish.ufo"
require "squish.todo_comments"
-- require "squish.aerial"
require "squish.renamer"
require "squish.eyeliner"
require "squish.lualine"
require "squish.truezen"
